language: node_js
node_js:
  - "6"
cache: yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm run start &
  - sleep 3
script:
  - npm test-ci
  - nightwatch --env ci
addons:
  firefox: "latest"
  sauce_connect:
    username: "FotiJr"
    access_key: "7f2e3b7f-d3ef-4e7d-88e8-369e306d3e07"    